<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPostsByCategory($id_category)
    {

        return $this->createQueryBuilder('p')
            ->where('p.isPublished = true')
            ->andWhere('p.isApproved = true')
            ->andWhere('p.category = :id_category')
            ->setParameter('id_category', $id_category)
            ->getQuery()
            ->getResult();

    }
}
