back_end:
    resource: "@BackEndBundle/Controller/"
    type:     annotation

front_end:
    resource: "@AppBundle/Controller/"
    type:     annotation

#FOSUser routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"