back_end:
    resource: "@BackEndBundle/Controller/"
    type:     annotation

front_end:
    resource: "@FrontEndBundle/Controller/"
    type:     annotation

#FOSUser routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#Sonata routing
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /mediaiipImagineBundle/Resources/config/routing.xml"